name: Weekly Crawler

on:
  schedule:
    # 매주 월요일 새벽 2시 (KST) = 일요일 17시 (UTC)
    - cron: '0 17 * * 0'
  workflow_dispatch: # 수동 실행 가능

jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 60 # 1시간 타임아웃

    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      CRAWL_DELAY: 0.3
      MAX_RETRIES: 3
      TIMEOUT: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: crawler/requirements.txt

      - name: Install dependencies
        run: |
          cd crawler
          pip install -r requirements.txt

      - name: Run CU crawler
        id: cu-crawler
        continue-on-error: true
        timeout-minutes: 30
        run: |
          cd crawler
          python upload_to_db.py cu

      - name: Run SevenEleven crawler
        id: seven-crawler
        continue-on-error: true
        timeout-minutes: 30
        run: |
          cd crawler
          python upload_to_db.py seven

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: crawler-logs
          path: crawler/logs/
          retention-days: 7
          if-no-files-found: warn

      - name: Check results
        if: always()
        run: |
          echo "=== Crawler Results ==="
          echo "CU: ${{ steps.cu-crawler.outcome }}"
          echo "SevenEleven: ${{ steps.seven-crawler.outcome }}"

          if [ "${{ steps.cu-crawler.outcome }}" == "failure" ] || [ "${{ steps.seven-crawler.outcome }}" == "failure" ]; then
            echo "⚠️ Some crawlers failed"
            exit 1
          else
            echo "✅ All crawlers completed successfully"
          fi
